### ISSUE TITLE
Add support for specifying config file location

### ISSUE THREAD

**Issue by kgryte** [mercos/codeclimate-pylint#110]
At the moment, this engine does not appear to support specifying a custom `pylint` configuration file location. Similar to other engines (e.g., CodeClimate's EditorConfig plugin), would be useful to be able to do so.

**Comment by caiofbpa** [comment]
Hey @kgryte thanks for the suggestion. We would love to review and merge a PR that accomplishes that.

**Comment by rafaeldalsanto** [comment]
I'm closing this issue because we're archiving this repository.
