### ISSUE TITLE
[QUESTION] How to ignore 'Unable to import'

### ISSUE THREAD

**Issue by vdsbenoit** [mercos/codeclimate-pylint#133]
Hi,

First of all, thank you for this great plugin! It is very helpful 🙇‍♂️

I would like to report an issue I face while using this plugin through the [CodeClimate integration in GitLab](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html). The plugin report that it was unable to import numpy. This is expected because the CI job where the plugin is executed runs into a docker container. The container is based on [this docker image](https://gitlab.com/gitlab-org/ci-cd/codequality), where the project requirements (e.g. numpy) are not installed.

![image](https://user-images.githubusercontent.com/44053930/161511055-1b264a22-2b7d-4e0b-a5c1-2c0e022853fb.png)

What is the recommended way to ignore such a warning ? 

I created [a sample project](https://gitlab.com/vdsbenoit/demo-codeclimate-pylint) with the error. Feel free to use it to trigger it by yourself if you want to. 

You can see that after running [this pipeline](https://gitlab.com/vdsbenoit/demo-codeclimate-pylint/-/pipelines/508253195), I get the warning listed in [the Code Quality report](https://gitlab.com/vdsbenoit/demo-codeclimate-pylint/-/pipelines/508253195/codequality_report). The report is based on the CodeClimate json report that is exported as [artifact in here](https://gitlab.com/vdsbenoit/demo-codeclimate-pylint/-/jobs/2287259103/artifacts/browse) too.

**Comment by caiofbpa** [comment]
Hello @vdsbenoit and thanks for reaching out!

Given codeclimate engines cannot access the network for security reasons (to avoid leaking your codebase to the internet and etc), we cannot `pip install` any requirements from your project, and it's impractical to try to guess all packages used by "most" projects and pre-install them.

So it's expected that pylint won't be able to import most libraries, numpy included. We have made some concessions for pylint plugins, which are specifically supported by the open source community, like `pylint-django` for example.

With that said, you can either:

1. Tell pylint to [ignore the error](https://pylint.pycqa.org/en/latest/user_guide/message-control.html) and move on
2. Find or build a pylint plugin for numpy and open a PR here adding support for it

I hope this helps!

**Comment by vdsbenoit** [comment]
Hi @caiofbpa,

I followed your advice and added a `.pylintrc` in my project as follows
````ini
[MESSAGES CONTROL]
disable = import-error
````

Thanks a lot for your support!
