### ISSUE TITLE
"No engine named pylint found"

### ISSUE THREAD

**Issue by maxdanilov** [mercos/codeclimate-pylint#63]
Here's my `.codeclimate.yml`:
```
engines:
  pylint:
    enabled: true
    channel: "beta"
```

Running this command:

```
codeclimate analyze
```

Results in the following message:
```
Starting analysis
Running pylint: Done!
Skipped pylint: No engine named pylint found

Analysis complete! Found 0 issues.
```

Codeclimate version: 0.85.6

UPD. Debug+dev mode:
```
$ CODECLIMATE_DEBUG=1 codeclimate analyze --dev
Starting analysis
I, [2020-01-03T18:02:50.407924 #1]  INFO -- : starting engine pylint
D, [2020-01-03T18:02:51.297806 #1] DEBUG -- : /config.json content: {"enabled"=>true, "config"=>"ruleset.groovy", "channel"=>"beta", "include_paths"=>["configfiles/", "codeclimate.txt", "all.groovy", "LICENSE", "ruleset.groovy", "diff-jobs.sh", ".java-version", "docs/", ".editorconfig", "README.md", "gradle/", "gradlew", ".gitignore", "add-new-minor-version.sh", ".github/", "build.gradle", "Jenkinsfile", ".gradle/", "jobs-plain/", ".tmp/", "jobs/", "gradlew.bat", "settings.gradle", "views/", ".codeclimate.yml", ".idea/", "src/config/", "src/main/"], "debug"=>"1"}
D, [2020-01-03T18:02:51.312649 #1] DEBUG -- : docker run: ["docker", "run", "--name", "cc-engines-pylint-beta-97028dea-1ab3-4ce5-8246-8f58bb748049", "--cap-drop", "all", "--label", "com.codeclimate.label=102b42d8-a5b1-4c86-8ca6-9d778a3a178d", "--log-driver", "none", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/Users/maxim.danilov/camunda/jenkins-job-dsl-seed-jobs:/code:ro", "--volume", "/tmp/cc/106346f1-f8f3-4fa7-b281-1e69281c934d:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-pylint"]
D, [2020-01-03T18:02:51.332523 #1] DEBUG -- : engine stderr: Unable to find image 'codeclimate/codeclimate-pylint:latest' locally
D, [2020-01-03T18:02:52.853151 #1] DEBUG -- : engine stderr: docker: Error response from daemon: manifest for codeclimate/codeclimate-pylint:latest not found: manifest unknown: manifest unknown.
D, [2020-01-03T18:02:52.853344 #1] DEBUG -- : engine stderr: See 'docker run --help'.
I, [2020-01-03T18:02:52.857248 #1]  INFO -- : finished engine pylint
error: (CC::CLI::Analyze::EngineFailure) engine pylint failed with status 125 and stderr
Unable to find image 'codeclimate/codeclimate-pylint:latest' locally
docker: Error response from daemon: manifest for codeclimate/codeclimate-pylint:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
D, [2020-01-03T18:02:52.857567 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `block in finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `each'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `finished'
	/usr/src/app/lib/cc/analyzer/bridge.rb:52:in `block (2 levels) in run'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:63:in `with_spinner'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:41:in `block in engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/formatter.rb:31:in `engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:40:in `engine_running'
	/usr/src/app/lib/cc/analyzer/bridge.rb:37:in `block in run'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `each'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `run'
	/usr/src/app/lib/cc/cli/analyze.rb:36:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:25:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:12:in `<main>'
```

**Comment by caiofbpa** [comment]
Have you tried without the `channel: "beta"`?

Maybe CodeClimate has considered this engine stable (and I didn't even know).

**Comment by maxdanilov** [comment]
@caiofbpa without beta it also does not work.

**Comment by caiofbpa** [comment]
I see. Well, the repositories are managed only by CodeClimate.

Perhaps @larkinscott can help us?

**Comment by larkinscott** [comment]
:wave: @maxdanilov @caiofbpa 

It looks like we have `codeclimate-pylint` pinned to a pretty old commit at this point. 

@caiofbpa I cloned this repo and built it locally, running `codeclimate analyze` in dev mode. It seems to be breaking on `Running pylint using PYTHONPATH`, though I'm not passing one in the config. I'm not too familiar with that part of the code, so my question is: would you expect that to happen if I'm not passing `PYTHONPATH` in the config or should it work regardless? 

All this to say, we could try updating to the latest commit on our end, but I just want to do some QA locally before going down that road. Thanks!

**Comment by larkinscott** [comment]
@caiofbpa I just realized that we mistakenly removed `codeclimate-pylint` from our CLI a while back when we were cleaning up some beta engines, which would account for the error @maxdanilov is seeing. Sorry about that! I can go ahead and promote this to stable and re-add it to the CLI after we debug the issue above.

**Comment by caiofbpa** [comment]
@larkinscott I pushed a fix to master, it should be working now.

**Comment by larkinscott** [comment]
@caiofbpa Thanks for the quick fix! Works great. I'll try to get this into production today.

cc: @maxdanilov

**Comment by caiofbpa** [comment]
@larkinscott if you manage to promote it to stable, let me know so I can update the documentation removing the `channel: "beta"`

**Comment by larkinscott** [comment]
@caiofbpa This will be released to `stable` shortly, so feel free to go ahead and update the docs. I kept the `beta` channel around for now so as not to break anything for any users who might be currently using it. I'll try to re-add it to the CLI by end-of-day.

**Comment by caiofbpa** [comment]
I've just updated the docs. @larkinscott any news on the official release?

**Comment by larkinscott** [comment]
@caiofbpa Just included it in the latest CLI release. You should be able to pull the newest CLI and run it with or without the beta key now.

**Comment by caiofbpa** [comment]
Thanks a lot @larkinscott!

@maxdanilov can you confirm that the engine is working for you now?

**Comment by szewczykmira** [comment]
Hi, I've had the same issue and after upgrading cli everything works ;)
Thanks!

**Comment by maxdanilov** [comment]
@larkinscott @caiofbpa works for me with 0.85.7, thank you 🎉
