### ISSUE TITLE
pylint-quotes support

### ISSUE THREAD

**Issue by Hudda** [mercos/codeclimate-pylint#64]
Is there a plan to support `pylint-quotes` with this engine?

**Comment by caiofbpa** [comment]
I've implemented it at #65, it should be merged soon

**Comment by caiofbpa** [comment]
Now we just have to wait for CodeClimate to update it's image

**Comment by caiofbpa** [comment]
@larkinscott can you help us with that?

**Comment by larkinscott** [comment]
@caiofbpa Apologies for the delay. Getting this into production now.
