### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by sigmavirus24** [mercos/codeclimate-pylint#86]
Hi y'all,

I'm looking at building an engine for Flake8 and was thinking of basing it off of your excellent work here. Before I started poking around, I wanted to check licenses would be compatible but y'all don't have one. So that means I can't fork your project, preserve copyright and alter it to work for Flake8. That also means contributions from others outside of mercos would be kind of questionable as there's nothing assigning copyright/trademark rights to your project and thus protecting it.

Did y'all overlook this or is this a deliberate decision?

Cheers,

**Comment by caiofbpa** [comment]
Hello @sigmavirus24, thanks for your issue. We have licensed this software under the MIT License, as per https://github.com/mercos/codeclimate-pylint/blob/master/LICENSE. Feel free to contribute or use it as is to create other engines. If you need anything else, just open another issue. Cheers!

**Comment by sigmavirus24** [comment]
Cheers!
